Revision: Numeration begins with 1 consistent with crest

diff --git a/crest2dft b/crest2dft
--- a/crest2dft
+++ b/crest2dft
@@ -40,9 +40,13 @@ function extract-xyz-from-file {
 																		#input: $coords[n], $INPUTFILE, $nproc, $crestconformers
 																		function create-multiple-job-input {
 
+																			jobtype=Opt
+																			if ! [[ -z $spe ]]; then jobtype='' ; fi
+
 																			for (( k=0 ; k < ${#coords[@]} ; k++ )); do
-	cat > TEMPHEAD <<?
-! B97-3c Grid5 NoFinalGrid Opt TightSCF
+																					i=$((k+1))
+																						cat > TEMPHEAD <<?
+! B97-3c Grid5 NoFinalGrid $jobtype TightSCF
 %scf
 Guess Hueckel
 end
@@ -51,8 +55,7 @@ end
 #echo "bugfix: TEMPHEAD: "$TEMPHEAD""
 
 #	INPUTBASE[$k]=%base'"'opt-crest"$k"_b97-3c'"'
-INPUTBASE[$k]=%base'"'opt-${crestconformers/.xyz}_"$k"_b97-3c'"'
-
+INPUTBASE[$k]=%base'"'opt-${crestconformers/.xyz}_"$i"_b97-3c'"'
 
 	cat > TEMPTECH <<?
 %MaxCore 2000
@@ -85,7 +88,7 @@ ${coords[$k]}
 					}
 
 					inputarr=($*)
-					crestconformers=crest_conformers.xyz
+					crestconformers=crest_conformers.xyz ### default XYZ-file containing conformers
 					inputcrestconformers=$1
 					INPUTFILE=$2
 					if [[ ! -f $inputcrestconformers ]] && [[ ! -f $crestconformers ]] ; then
@@ -97,6 +100,10 @@ ${coords[$k]}
 									crestconformers=$inputcrestconformers
 								fi
 
+								checkxyz=$(echo $crestconformers | rev | cut -f1 -d'.' | rev | sed 's/xyz/yes/')
+								if ! [[ $checkxyz = "yes" ]]; then echo "Input-File must be an .xyz file. Aborting."; exit ; fi
+								### $crestconformers exists and is a ".xyz"-file
+
 								if [[ -z $2 ]]; then 
 										INPUTFILE=crest2dft_b97-3c.inp
 									fi
@@ -105,33 +112,20 @@ ${coords[$k]}
 												exit
 											fi
 
-											nproc=$(echo ${inputarr[@]} | tr -s ' ' '\n' | grep -E '^-n[0-9]+' | sed 's/-n//')
+											nproc=$(echo ${inputarr[@]} | tr -s ' ' '\n' | grep -E '^-n[0-9]+$' | sed 's/-n//')
 											if [[ -z $nproc ]] ; then nproc=4 ; fi
 
-											while getopts "n:h" OPTION; do
-												        case $OPTION in
-																h) echo "Flag under construction."
-																			;;
-																			        n)	nproc=$OPTARG
-																								if ! [[ "$nproc" =~ ^[0-9]+$ ]]; then
-																													echo "Invalid format for '-n': Number of processors must be an Integer."
-																																	echo "Aborting."
-																																					exit
-																																								fi
-																																								         ;;
-																																									 		\?) echo "Invalid option: -$OPTARG"; exit
-																																												        ;;
-																																													        esac
-																																													done
+											spe=$(echo ${inputarr[@]} | tr -s ' ' '\n' | grep -E -i '^-SPE$' | sed 's/-//')
 
 
-																																													echo "Reading CREST-conformers: $crestconformers"
-																																													extract-xyz-from-file
-																																													for (( i=0 ; i < ${#coords[@]} ; i++ )) ; do
-																																															echo "${coords[$i]}" >> ${crestconformers/.xyz}_$i.xyz
-																																														done
-																																														echo "... saved in ${crestconformers/.xyz}_[i].xyz (i=0,...)" 
-																																														create-multiple-job-input
+											echo "Reading CREST-conformers: $crestconformers"
+											extract-xyz-from-file
+											for (( i=0 ; i < ${#coords[@]} ; i++ )) ; do
+													k=$((i+1))
+														echo "${coords[$i]}" >> ${crestconformers/.xyz}_$k.xyz
+													done
+													echo "... saved in ${crestconformers/.xyz}_[i].xyz (i=1,...)" 
+													create-multiple-job-input
 
 
 
